template = "https://github.com/giellalt/template-lang-und"
rev_id = 267
template_sha = "eecc8ba78a1297394fa54b425d94002ee6604eb1"

[replacements]
__GLOTTOLOG_ID__ = "ikpe1245"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-txi"
__UND2C__ = "txi"
__UNDEFINED__ = "Ikpeng"
__UND__ = "txi"
