template = "https://github.com/giellalt/template-lang-und"
rev_id = 208
template_sha = "8692838fc7cf77fe5ec2a217ecdaea7f79547a51"

[replacements]
__LICENSE__ = "GPLv3"
__REPO__ = "lang-txi"
__UND2C__ = "txi"
__UNDEFINED__ = "Ikpeng"
__UND__ = "txi"
