template = "https://github.com/giellalt/template-lang-und"
rev_id = 277
template_sha = "c0f383639e245d1daebce6e2006904e442eef1fd"

[replacements]
__GLOTTOLOG_ID__ = "ikpe1245"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-txi"
__UND2C__ = "txi"
__UNDEFINED__ = "Ikpeng"
__UND__ = "txi"
