template = "https://github.com/giellalt/template-lang-und"
rev_id = 268
template_sha = "444a55f5c0c0489e8f1dcde2639b74c44c24dffb"

[replacements]
__GLOTTOLOG_ID__ = "ikpe1245"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-txi"
__UND2C__ = "txi"
__UNDEFINED__ = "Ikpeng"
__UND__ = "txi"
